### ISSUE TITLE
The MOTD should be red only if it takes longer than the maximum splay

### ISSUE THREAD

**Issue by evaryont** [chr4-cookbooks/motd#10]
Currently, the MOTD is red if chef hasn't ran in longer than the interval, but that is only the minimum amount of time between runs, there is a random number of seconds after which chef will actually run. I feel like the MOTD should only be red if chef hasn't run in interval + splay minutes, not just interval.

**Comment by chr4** [comment]
This is included in `0.6.2`. Thanks!
