### ISSUE TITLE
release v1+ on supermarket

### ISSUE THREAD

**Issue by BarthV** [chr4-cookbooks/motd#13]

**Comment by chr4** [comment]
Can you explain what you mean? I'm not quite getting it, I'm afraid...

**Comment by BarthV** [comment]
latest motd on Chef's supermarket is 0.6.1 :
https://supermarket.chef.io/cookbooks/motd

Tags v1.0.0 & v1.0.1 are missing so thay cannot be resolved by dependency manager :)

Maybe you can upload it if v1.0.0 is final & ready to go

**Comment by chr4** [comment]
This is correct. The current version is 0.6.1 (see metadata.rb in this repository).
Can you point out what your dependency manager is trying to do? Is there another cookbook requiring a "motd" cookbook with version v1.0.0?

**Comment by BarthV** [comment]
ok my bad ;-/ I was tricked by thoses "v1" tags. I didn't test this before... sry

If 0.6 is current so it's ok for me.

**Comment by chr4** [comment]
Ah now I get it. Those tags we're from a pull-request. I must have pushed them by accident. This is confusing, you're right. :(

**Comment by chr4** [comment]
Deleted them. Thanks for pointing out!
