### ISSUE TITLE
Support for bash scripts on RHEL/CentOS

### ISSUE THREAD

**Issue by philicious** [chr4-cookbooks/motd#17]
as RHEL/CentOS doesnt support bash scripts in `/etc/motd` one needs to branch code when you need bash scripts in motd.

As a solution, you could check for `#!` in first line and then render template to `/etc/profile.d/motd.sh` instead of `/etc/motd` if `platform_family?('rhel')`

**Comment by chr4** [comment]
I'm not quite sure I'm getting this right. 
Does RHEL support bash scripts in `/etc/profile.d/motd.sh`?
As far as I know, no distribution supports bash scripts in `/etc/motd`. There's `update-motd` for Ubuntu, which assembles `/etc/motd` dynamically.

I'm not very familiar with RHEL, would you mind elaborating the issue a little more?
A small pull-request or code snipped of your suggested fix would also help.

Thanks for reporting!

**Comment by philicious** [comment]
yes you are right. I wasnt precise enough:
Ubuntu uses `update-motd` for bash scripts in motd. For RHEL you would use `/etc/profile.d/motd.sh` which has the same effect then.
Unfortunately I dont have the time (in office) atm for a proper PR. However let me show you how I fixed it which is adaptable to your LWRP:

```
# you could do it this way or check if the template contains #! on first line
# if not, then it can go to /etc/motd

# the public cookbook "motd" works for CentOS/RHEL, however it doesnt support
# bash scripts as motd for RHEL
if platform_family?('debian')
  motd '80-foobar' do
    cookbook 'foobar'
    source 'motd.erb'
    variables(
		# some variables
    )
  end
elsif platform_family?('rhel') 
  template '/etc/profile.d/motd.sh' do
    action :create
    owner  'root'
    group  'root'
    mode 0755
    source 'motd.erb'
    variables(
		# some variables
    )
  end
end
```

**Comment by chr4** [comment]
Another way would be to check whether RHEL supports `/etc/profile.d/motd.sh` and then just deploy a dynamic version, similar to how it's currently done using `update-motd.d`.
I'm not confortable implementing this on my own, as I do not use RHEL. 
I'll keep this open until someone will create a proper pull-request.

**Comment by philicious** [comment]
I'll try to do a proper PR this week then. Might be towards weekend tho

**Comment by chr4** [comment]
Closing this in favor of https://github.com/chr4-cookbooks/motd/pull/18
