### ISSUE TITLE
Problems with chef_handler

### ISSUE THREAD

**Issue by ares** [chr4-cookbooks/motd#22]
Using the motd 0.6.4 I'm getting following with chef-client 13.0

================================================================================
    Error executing action `enable` on resource 'chef_handler[Motd::KnifeStatus]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `new' for ChefHandler:Module
    
    Cookbook Trace:
    ---------------
    /var/cache/chef/cookbooks/chef_handler/providers/default.rb:58:in `load_current_resource'
    
    Resource Declaration:
    ---------------------
    # In /var/cache/chef/cookbooks/motd/recipes/knife_status.rb
    
     56: chef_handler 'Motd::KnifeStatus' do
     57:   source ::File.join(Chef::Config[:file_cache_path], 'handlers', 'knife_status.rb')
     58:   action :enable
     59: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/cache/chef/cookbooks/motd/recipes/knife_status.rb:56:in `from_file'
    
    chef_handler("Motd::KnifeStatus") do
      action [:enable]
      default_guard_interpreter :default
      supports {:report=>true, :exception=>true}
      declared_type :chef_handler
      cookbook_name "motd"
      recipe_name "knife_status"
      source "/var/cache/chef/handlers/knife_status.rb"
      class_name "Motd::KnifeStatus"
    end
    
    System Info:
    ------------
    chef_version=13.0.113
    platform=debian
    platform_version=8.7
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=613;start=11:24:03;
    executable=/opt/chef/bin/chef-client

**Comment by chr4** [comment]
Thanks for the report!
This seems to be an issue with `chef_handler`, someone already reportet an issue [here](https://github.com/chef-cookbooks/chef_handler/issues/50).

The only intermediate solution that comes to my mind currently is version-lock chef to 12.x until this is resolved.

If someone knows how to quickly install the chef-handler using another method, please report!

**Comment by ares** [comment]
Thanks for workaround. It's not critical :-)

**Comment by chr4** [comment]
@ares: According to to https://github.com/chef-cookbooks/chef_handler/issues/50, a fix for this bug has been shipped. Can you check whether it is gone with the latest update? 
Let me know and/ or close the issue if it works again.

**Comment by ares** [comment]
Sorry I don't have the setup right now. I'll let you know if I encounter it again, but I think it'll be ok.
