### ISSUE TITLE
chef_handler cookbook has been deprecated, causing cookstyle to fail

### ISSUE THREAD

**Issue by Lasering** [chr4-cookbooks/motd#25]
Cookstyle fails with:

`ChefModernize/UnnecessaryDependsChef14: Don't depend on cookbooks made obsolete by Chef Infra Client 14+. These community cookbooks contain resources that are now included in Chef Infra Client itself. depends 'chef_handler', '= 3.0.3'`

The [chef_handle cookbook](https://supermarket.chef.io/cookbooks/chef_handler) has been deprecated and is no longer being maintained by Chef.

The chef client can now implement handlers out of the box: https://docs.chef.io/handlers/

I can make a PR with the necessary changes.

**Comment by chr4** [comment]
Thanks for the report! I'd very much apprechiate a pull request to fix this, looking forward to it!
